### ISSUE TITLE
Help to Setup and Use

### ISSUE THREAD

**Issue by WeakCode777** [foximler/AnswerBot#1]
sir please provide step how to use this ?

**Comment by foximler** [comment]
Give the bot your chegg login info. Install selenium and setup a discord bot and give the script the api key. Then just run the script and use  !AMAK followed by the url to ask it questions.

**Comment by WeakCode777** [comment]
> Give the bot your chegg login info. Install selenium and setup a discord bot and give the script the api key. Then just run the script and use !AMAK followed by the url to ask it questions.

its not working sir I try it so Many time , I always Encounter and error :(( can you help me ?

**Comment by WeakCode777** [comment]
> Give the bot your chegg login info. Install selenium and setup a discord bot and give the script the api key. Then just run the script and use !AMAK followed by the url to ask it questions.

I already Change the User and Password to premium chegg ,
I already Change the discord token to my BOT TOKEN


![image](https://user-images.githubusercontent.com/52873267/101733929-8a369500-3afa-11eb-848c-d55e18e2e34a.png)

**Comment by foximler** [comment]
That's an issue with your install. Not my code.
